<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>14</LangVersion>
		<IsAotCompatible>true</IsAotCompatible>

		<OutputType>Library</OutputType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<RootNamespace>OceanApocalypseStudios.RedSea.Cli</RootNamespace>

		<!-- Native Publishing -->
		<PublishAot>true</PublishAot>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<TieredCompilation>true</TieredCompilation>

		<IsPackable>true</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(PublishAot)' == 'true'">
		<DefineConstants>$(DefineConstants);NATIVE_AOT</DefineConstants>
		<InvariantGlobalization>true</InvariantGlobalization>
		<OptimizationPreference>Size</OptimizationPreference>
		<StripSymbols>true</StripSymbols>
	</PropertyGroup>

	<PropertyGroup Label="Debug Build" Condition="'$(Configuration)' == 'Debug'">
		<DebugType>full</DebugType>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<PropertyGroup Label="Release (Optimized) Build" Condition="'$(Configuration)' == 'Release'">
		<DebugType>none</DebugType>
		<Optimize>true</Optimize>
	</PropertyGroup>

	<ItemGroup Label="Resources">
		<None Include="..\..\assets\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
	</ItemGroup>

	<PropertyGroup>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackAsTool>true</PackAsTool>

		<PackageId>OceanApocalypseStudios.RedSeaEngine.Cli</PackageId>
		<Title>Red Sea Engine CLI</Title>
		<ToolCommandName>rsea</ToolCommandName>
		<ToolPackageRuntimeIdentifiers>win-x64;win-arm64;win-x86;osx-arm64;osx-x64;linux-x64;linux-arm64;linux-arm;any</ToolPackageRuntimeIdentifiers>
		<Authors>OceanApocalypseStudios</Authors>
		<Company>OceanApocalypseStudios</Company>
		<NeutralLanguage>en</NeutralLanguage>

		<!-- DON'T FORGET TO EDIT THIS -->
		<Version>1.0.0-prerelease1</Version>
		<InformationalVersion>1.0.0-prerelease1</InformationalVersion>
		<PackageReleaseNotes>TODO</PackageReleaseNotes>

		<Description>The CLI for the engine that handles cross-platform targets with incredible ease.</Description>
		<Copyright>Copyright (c) 2026 OceanApocalypseStudios</Copyright>
		<PackageProjectUrl>https://oceanapocalypsestudios.org/RedSeaEngine/</PackageProjectUrl>
		<PackageIcon>icon.png</PackageIcon>
		<RepositoryUrl>https://github.com/OceanApocalypseStudios/RedSeaEngine/</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>evaluation;logic;logic-path;system;host;oss</PackageTags>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

</Project>
