<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
		<RootNamespace>OceanApocalypse.RedSea.Tests</RootNamespace>
		<TargetFramework>net10.0</TargetFramework>
		<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.0" />
		<PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\RedSeaEngine.Native\RedSeaEngine.Native.csproj" />
	  <ProjectReference Include="..\..\src\RedSeaEngine\RedSeaEngine.csproj" />
	</ItemGroup>

</Project>
