<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>14</LangVersion>
		<IsAotCompatible>true</IsAotCompatible>

		<OutputType>Library</OutputType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<RootNamespace>OceanApocalypse.RedSea</RootNamespace>

		<!-- Native Publishing -->
		<PublishAot>true</PublishAot>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<NativeLib>Shared</NativeLib>
		<InvariantGlobalization>true</InvariantGlobalization>
		<TieredCompilation>true</TieredCompilation>
		<PublishSingleFile>false</PublishSingleFile>

		<IsPackable>true</IsPackable>
	</PropertyGroup>

	<PropertyGroup Label="Debug Build" Condition="'$(Configuration)' == 'Debug'">
		<DebugType>full</DebugType>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<PropertyGroup Label="Release (Optimized) Build" Condition="'$(Configuration)' == 'Release'">
		<DebugType>none</DebugType>
		<Optimize>true</Optimize>
	</PropertyGroup>

	<ItemGroup Label="Resources">
		<None Include="..\..\assets\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
	</ItemGroup>

	<PropertyGroup>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>

		<PackageId>OceanApocalypse.RedSeaEngine.Native</PackageId>
		<Title>Native Support for Red Sea Engine</Title>
		<Authors>OceanApocalypse</Authors>
		<Company>OceanApocalypse</Company>
		<NeutralLanguage>en</NeutralLanguage>

		<!-- DON'T FORGET TO EDIT THIS -->
		<Version>1.0.0-prerelease1</Version>
		<InformationalVersion>1.0.0-prerelease1</InformationalVersion>
		<PackageReleaseNotes>TODO</PackageReleaseNotes>

		<Description>The engine made for handling cross-platform targets with incredible ease.</Description>
		<Copyright>Copyright (c) 2026 OceanApocalypse</Copyright>
		<PackageProjectUrl>https://oceanapocalypse.org/RedSeaEngine/</PackageProjectUrl>
		<PackageIcon>icon.png</PackageIcon>
		<RepositoryUrl>https://github.com/OceanApocalypse/RedSeaEngine/</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>evaluation;logic;logic-path;system;host;oss</PackageTags>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

</Project>